- name: instala apache y php para servidores Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: instala apache y php para servidores Rocky
  tags: apache,rocky,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "Rocky"

- name: start httpd (Rocky)
  tags: apache,rocky,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Rocky"

- name: cambiar direccion de  e-mail  del admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == 'Rocky'
  register: consultaestadohttpd

- name: reiniciar httpd (rocky)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: consultaestadohttpd.changed


- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
