- name: instalar paquete mariadb (Rocky)
  tags: rocky,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: instalar paquete mariadb (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
